spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/spring-study
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace